### ISSUE TITLE
Request: Generate environment section for a job

### ISSUE THREAD

**Issue by johnmurphy01** [CircleCI-Public/circleci-config-sdk-ts#130]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to be able to specify environment variables within a job: https://circleci.com/docs/env-vars#setting-an-environment-variable-in-a-job

From what I can tell, this doesn't appear to be supported. I can add a step and define a parameter but I don't see a method for `addEnvironment` or `defineEnvironment`

### Describe the solution you'd like

Essentially a new chainable method on a job where I can `defineEnvironment` 

### Teachability, documentation, adoption, migration strategy

```ts
job
.addStep(checkoutStep)
.defineParameter('a_parameter', 'string', 'value', 'description')
.defineEnvironment('A_ENV_VARIABLE', 'a value')
```

### What is the motivation / use case for changing the behavior?

This is part of Circle CI and I am attempting to generate an existing yaml file using this library and I need the ability to specify environment variables.

**Comment by KyleTryon** [comment]
Love it, thanks for the suggestion @johnmurphy01. I'll add this.

Looks like we somehow left environment variables out of the job definition, we'll get this all fixed up

**Comment by KyleTryon** [comment]
I am going to propose we use `addEnv` or a variation of this (`addEnvVar`, `addVariable`).

My reasoning being that `defineParameter` refers to defining the definition of a parameter in a reusable job (which, an aside, is not typically needed in a JS based config but we include this for parsing existing YAML configs) but it is not responsible for setting the value of the parameter on the WorkflowJob which gets invoked.

`addStep` in contrast defines the value of the steps within the job.

As we are defining the value of an environment within the job, I think using the `add` language used in `addStep` is more appropriate.

**Comment by KyleTryon** [comment]
Just merged in the change @johnmurphy01 
We'll push a new version soon, we have a few items to clear up.
https://github.com/CircleCI-Public/circleci-config-sdk-ts/pull/132

**Comment by johnmurphy01** [comment]
@KyleTryon works great, thanks!
