### ISSUE TITLE
Bug: Job parallelism property is not displayed 

### ISSUE THREAD

**Issue by tapesec** [CircleCI-Public/circleci-config-sdk-ts#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The parallelism option is supposed to available for a job.
This parallelism property is available into the Job class constructor but it is not passed to the generateContents method so you can’t see it in the final generated .yml config.

### Minimum reproduction code

[<script src="https://gist.github.com/tapesec/a2ba9bce9b2ca88542bd4cc05edca154.js"></script>
](https://gist.github.com/tapesec/a2ba9bce9b2ca88542bd4cc05edca154)

### Expected behavior

The parallelism property passed to the Job class constructor is not returned from the generateContents method.
I added it.

### CircleCI Config SDK version

v0.9.0-alpha.21

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tapesec** [comment]
I’ve created a PR to fix it but I can’t push it because I haven’t access right. Could you grant me up please ?

**Comment by KyleTryon** [comment]
Hey @tapesec You should be able to open a PR from a fork without any special access. Could you link us to your branch on GitHub?

**Comment by tapesec** [comment]
![Screenshot 2022-09-13 at 10 26 43](https://user-images.githubusercontent.com/4386903/189851220-c12ee095-083a-41df-8893-d0dc9e94c916.png)
Hey Kyle 👋 I can’t push my branch at all

**Comment by tapesec** [comment]
Oh sorry my bad I cloned the repo I didn’t fork it :(

**Comment by KyleTryon** [comment]
Closed in #139
