### ISSUE TITLE
Request: add support for docker_layer_caching in machine executor

### ISSUE THREAD

**Issue by a-cordier** [CircleCI-Public/circleci-config-sdk-ts#146]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It looks like generating a machine executor from the SDK does not allow to define the [docker_layer_caching](https://circleci.com/docs/docker-layer-caching#machine-executor) property.

The [MachineExecutorShape](https://github.com/CircleCI-Public/circleci-config-sdk-ts/blob/46cb714805635beef06e402d1f3ddeab8f15f225/src/lib/Components/Executors/types/MachineExecutor.types.ts#L4) object defines this property, but it is not handled by the [generateContent](https://github.com/CircleCI-Public/circleci-config-sdk-ts/blob/46cb714805635beef06e402d1f3ddeab8f15f225/src/lib/Components/Executors/exports/MachineExecutor.ts#L23) method in the executor itself.

### Describe the solution you'd like

Maybe adding a `useDockerImageLayerCaching` method to the MachineExecutor class

```typescript
export class MachineExecutor extends Executor<MachineResourceClass> {
  image = 'ubuntu-2004:202010-01';
  docker_layer_caching?: boolean;

  generateContents(): MachineExecutorShape {
    return {
      image: this.image,
      docker_layer_caching: this.docker_layer_caching,
    };
  }
  
  // [..]

  withDockerLayerCaching(activate: boolean): MachineExecutor {
    this.docker_layer_caching = activate;
    return this;
  }
}
```

## Enabling docker image layer caching on machine executors

```typescript
const myConfig = new CircleCI.Config();
const machine = new CircleCI.executors.MachineExecutor('large').withDockerLayerCaching(true);
const const reusableMachine = new CircleCI.reusable.ReusableExecutor('default', machine);

myConfig.addReusableExecutor(reusableMachine);
```

### What is the motivation / use case for changing the behavior?

We are considering using the SDK to generate our continuation step and need this feature to match our existing config file

**Comment by KyleTryon** [comment]
Closed by #147, thanks again @a-cordier! Looking forward to seeing your avatar on the contributor's list.
