### ISSUE TITLE
Bug: Executor generateContents method doesn’t return more than one image

### ISSUE THREAD

**Issue by tapesec** [CircleCI-Public/circleci-config-sdk-ts#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you call the .generate method from an Executor instance and you have add more than one Image, the `generate` method returns only the first one.

### Minimum reproduction code

https://gist.github.com/tapesec/5d25e351e6528426b16a91ef2360ee63

### Expected behavior

The Executor instance should return as much ImageService as has been added.
[Here](https://github.com/CircleCI-Public/circleci-config-sdk-ts/pull/149) is the link to the related Fix I’ve done

### CircleCI Config SDK version

0.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by tapesec** [comment]
[Here](https://github.com/CircleCI-Public/circleci-config-sdk-ts/pull/149) the link to the PR I’ve done to fix it.

**Comment by KyleTryon** [comment]
Highly appreciate your help, sorry it took so long. v0.11.1 is publishing right now with your fix included!
