### ISSUE TITLE
Bug: Error: Cannot find module '@circleci/circleci-config-sdk/dist/src/lib/Components/Executors/exports/DockerImage'

### ISSUE THREAD

**Issue by mstva** [CircleCI-Public/circleci-config-sdk-ts#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```shell
yarn run v1.22.17
$ ts-node index.ts -f ../../.circleci/config.yml
Error: Cannot find module '@circleci/circleci-config-sdk/dist/src/lib/Components/Executors/exports/DockerImage'
Require stack:
- /myproject/scripts/generate_circleci_config/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (myproject/scripts/generate_circleci_config/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (myproject/scripts/generate_circleci_config/index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (myproject/scripts/generate_circleci_config/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (myproject/scripts/generate_circleci_config/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'myproject/scripts/generate_circleci_config/index.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Minimum reproduction code

https://gist.github.com/mstva/d2abbae90e9d60b4d485386bbe2f5832

### Expected behavior

it should give me the job like this

```ymal
version: 2.1
setup: false
jobs:
  run_unit_tests:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:13.8
```

### CircleCI Config SDK version

0.11.1

### Node.js version

18.11.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Jaryt** [comment]
Thanks for reporting this! I'll double check and make sure the docker types are being exported properly.

**Comment by Gray-Wind** [comment]
I came up with this usage, did not find how to directly import `DockerExecutor`

```ts
import {
  executors,
} from "@circleci/circleci-config-sdk";

const executor = new executors.DockerExecutor("imageName", "size")
```

**Comment by mstva** [comment]
> Thanks for reporting this! I'll double check and make sure the docker types are being exported properly.

I see that the pull request you linked seems to fix the issue, what is the problem with it? are you willing to merge it soon?

**Comment by mstva** [comment]
> I came up with this usage, did not find how to directly import `DockerExecutor`
> 
> ```ts
> import {
>   executors,
> } from "@circleci/circleci-config-sdk";
> 
> const executor = new executors.DockerExecutor("imageName", "size")
> ```


@Gray-Wind 

I think you could do that like this as well

```typescript
const CircleCI = require('@circleci/circleci-config-sdk');
new CircleCI.executors.DockerExecutor("imageName", "size")
```

but this is not the problem here, we have a problem in importing some types like the `DockerImage` that the issue talking about, it even not available through `new CircleCI` types.

so hope that the pull request that @Jaryt linked fixes it and merge it soon

**Comment by KyleTryon** [comment]
Hey all, 

v0.12.0 is now out!

GitHub: https://github.com/CircleCI-Public/circleci-config-sdk-ts/releases/tag/v0.12.0
NPM: https://www.npmjs.com/package/@circleci/circleci-config-sdk

**Comment by mstva** [comment]
for anyone who wants to use it, you could use it like this:

```python
const postgres_image = new CircleCI.types.executors.docker.DockerImage("cimg/postgres:13.8")
```

**Example:**

```python
const CircleCI = require('@circleci/circleci-config-sdk');
const circleci_config = new CircleCI.Config()

const postgres_image = new CircleCI.types.executors.docker.DockerImage("cimg/postgres:13.8")

const docker_python = new CircleCI.executors.DockerExecutor("cimg/python:3.10")
docker_python.addServiceImage(postgres_image)

const job = new CircleCI.Job(`run_unit_tests`, docker_python)
circleci_config.addJob(job)

console.log(circleci_config.stringify())
```

will produce a config file like this:

```yaml
version: 2.1
setup: false
jobs:
  run_unit_tests:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:13.8

```
