### ISSUE TITLE
Feedback: Multiline commands are inconsistent

### ISSUE THREAD

**Issue by cdhunt** [CircleCI-Public/circleci-config-sdk-ts#57]
### Version

0.4.0

### Describe your experience

I've created a few steps with multiline command strings.

```typescript
        new CircleCI.commands.Run({
            command: `blah
blah` }))
```

Some use the literal style `|` indicator and some use the chomping `>` indicator. What determines that and is it controllable?

**Comment by KyleTryon** [comment]
We discovered the issue was related to the string formatting used in the YAML library we were using. We have upgraded the YAML library and changed the string "type" to `BLOCK_LITERAL`. Changes will be in #64 shortly and included in the next update. Thank you 🙇

**Comment by KyleTryon** [comment]
Changes are present here with new tests: https://github.com/CircleCI-Public/circleci-config-sdk-ts/pull/64/commits/f8ba48255d45c0c1034689e792f16bede8cbe6f6

PLAIN actually did end up being a better option as far as we can tell so far, but we have found additional options which seem to influence line length.  Tested and added 👍 

Will leave this open until the branch is merged for visibility.
